### PR TITLE
tasks: add stop_workflow from reana_commons

### PR DESCRIPTION
**Pull request by diegodelemos**
Connects reanahub/reana-client#194.

### CODE REVIEW

**Comment by dinosk** [comment]
Depends on https://github.com/reanahub/reana-commons/pull/66

**Comment by dinosk** [comment]
Something prevents the status to be updated to `stopped` when the workflow is running.
Tested with `roofit` and `worldpopulation`, starting the workflow and then calling `reana-client stop --force` will log:
```
[2018-11-23 11:09:40,544: ERROR/MainProcess] Task handler raised error: Terminated(15,)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 1725, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: 15
```
all fine but `reana-client status` or querying the DB table shows it as running. Calling `reana-client stop --force` one more time does register it properly as `stopped`. @diegodelemos do you see the same? Happening for me only for yadage workflows, cwl and serial are ok

**Comment by diegodelemos** [comment]
@dinosk yadage is the only one I didn't actually test, I just propagated the changes there taking for granted that they would work as they do for the rest, shall we just create an issue about it?

**Comment by dinosk** [comment]
@diegodelemos I am not sure where it is rooting from but it is in this PR group and end user functionality won't be the same, so we could at least see how much time would be required to fix it. If the problem is too complex we could also open the issue and delay the feature for yadage workflows too as an option?

**Comment by diegodelemos** [comment]
@dinosk confirmed, it happens to me as well, I will take a look...

**Pull request merged**
