### PR TITLE
REANA Progress Tracking

### PR DESCRIPTION
**Pull request by lukasheinrich**
This adds a tracker stub for REANA progress tracking (switching from old zmq based tracking)
The messages are hard coded for now to test integration and will be replaced by actual
content once the connection is tested

### CODE REVIEW

**Comment by lukasheinrich** [comment]
I can't reproduce the import order messages locally. On Lxplus I get a message indicating that everything is fine


```
(venv)lheinric@lxplus074:../lheinric/reana-workflow-engine-yadage% isort -rc -c -df **/*.py; echo $?  
Skipped 1 files
0
```

**Comment by lukasheinrich** [comment]
is anything missing here @dinosk ?

**Comment by dinosk** [comment]
@lukasheinrich there’s one isort error, we need to rebase it on latest master and squash probably everything down to 2-3 commits, sth like: 1. New tracker 2. Publish status to MQ? Ill take care of rebasing and squashing in a bit, if you could fix travis in the meantime it’d help

**Comment by lukasheinrich** [comment]
done. PTAL.

**Pull request merged**
