### PR TITLE
installation: use yadage-fork

### PR DESCRIPTION
**Pull request by diegodelemos**
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

### CODE REVIEW

**Comment by lukasheinrich** [comment]
Hi @diegodelemos,

is there a specific feature you needed in the fork? I'm sure we can provide it within the main package?

Cheers,
Lukas

**Comment by diegodelemos** [comment]
@lukasheinrich  actually not, but for speed purposes we did it since you were on holidays. The change remained small (see https://github.com/diegodelemos/yadage/commit/3bb0a1b2e1cbe91c20f69560ea1d6193b5d60b20 ) but still we don't know what is the impact inside `yadage`. If you want we can open a PR

**Comment by diegodelemos** [comment]
Moreover, this is not the proper fix... we would need some more work to properly add support to submit workflow specs instead of pulling from GitHub

**Comment by lukasheinrich** [comment]
Hi @diegodelemos 

yadage 0.12.12 is now on PyPi and should support this:

https://pypi.python.org/pypi/yadage/0.12.12

**Pull request merged**
